language: node_js
node_js:
  - "10"
env:
  global:
    - MAX_SHARED_STORIES=30
    - MAX_COMMENTS=30
    - MAX_FILTER_STORIES=15
    - PASSWORD_SALT_ROUNDS=10
    - PORT=3000
    - MAX_GLOBAL_STORIES=300
    - POPULATE_STORY_INTERVAL_HOURS=6
    - DELETE_SHARED_STORY_INTERVAL_HOURS=15
    - EXPIRE_DAYS=2
install:
- npm install
- npm run build
script:
- npm test